### ISSUE TITLE
CAD code required

### ISSUE THREAD

**Issue by fulingly** [wenyalintw/Nodule-CADx#1]
Hello, Mr. Lin. First of all, your work is great. Thank you for sharing, but some links are missing. I also need to build a CAD system. I want to refer to your code. Can you share your code? thank you very much.

**Comment by wenyalintw** [comment]
Appreciate!
I haven’t upload the code since part of the project is ready to publish, I will upload full code as soon as possible, sorry for your inconvenience!

**Comment by wenyalintw** [comment]
Hi, FYI, I just upload the CAD code!

**Comment by fulingly** [comment]
What a big surprise, although I have graduated, hahaha, I will study it when I have time, thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wen-Ya Lin (林温雅)"<notifications@github.com&gt;; 
发送时间: 2020年12月17日(星期四) 上午8:43
收件人: "wenyalintw/Nodule-CADx"<Nodule-CADx@noreply.github.com&gt;; 
抄送: "2430530276"<2430530276@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wenyalintw/Nodule-CADx] CAD code required (#1)





 
Hi, FYI, I just upload the CAD code!
